[project]
name = "mcp-auth-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.122.0",
    "fastmcp>=2.13.1",
    "sqlalchemy>=2.0.44",
    "stytch>=13.28.1",
]
